#!/bin/sh
# Script that detects Operating System and output specific flags in a
# "platform.mk" file

# Which OS are we on?
OS=`uname -s | cut -c 1-7`

CF="CFLAGS +="
LDF="LDFLAGS +="

case $OS in
	"Linux")
		# Nothing specific
		;;
	"FreeBSD")
		CF="$CF -I/usr/local/include -lintl"
		LDF="$LDF -L/usr/local/lib"
		;;
	"Darwin")
		# TODO
		;;
	*)
		echo 'Sorry, OS currently unsupported'
		;;
esac

echo $CF > platform.mk
echo $LDF >> platform.mk
