.TH dfc 1  "March 27, 2012" "version 2.0.0" "USER COMMANDS"
.SH NAME
dfc \- display file system space usage using graph and colors colors
.SH SYNOPSIS
.B dfc [OPTION(S)]
.SH DESCRIPTION
dfc is a tool similar to df(1) except that it displays a graph along with the
data and is able to use colors.
The available size correspond to the space available to a user point of
view and not from root's perspective (ie: use f_bavail instead of f_bfree).
In the same idea, used space is computed simply by substracting the available
space from the total size.

Without any argument, size is displayed in human readable format.
Be aware that when using human-readable format, there might be some rounding
when computing the size. If you want a maximum precision, use one of the
options that displays size using SI units instead.
.SH OPTIONS
.TP
\-a
Display informations about all filesystem found in the mtab file.
.TP
\-b
Display size in Bytes.
.TP
\-c
Disable color.
.TP
\-g
Display size in Gio (powers of 1024).
.TP
\-G
Display size in Go (powers of 1000).
.TP
\-h
Display a short help text.
.TP
\-i
Display information about inodes.
.TP
\-k
Display size in Kio (powers of 1024).
.TP
\-K
Display size in Ko (powers of 1000).
.TP
\-m
Display size in Mio (powers of 1024).
.TP
\-M
Display size in Mo (powers of 1000).
.TP
\-n
Do not print header.
.TP
\-o
Show mount options.
.TP
\-s
Sum the total usage.
.TP
\-t
Hide filesystem type.
.TP
\-v
Print dfc version and exit.
.TP
\-w
Use a wider bar.
.SH BUGS
If you find one, please contact the author and explain what you encounter.
.SH AUTHORS
Robin Hahling (robin.hahling (at) gw-computing.net)
.SH COPYRIGHT
Copyright \(co 2012 Robin Hahling
.SH LICENSE
3 Clauses BSD
.SH SEE ALSO
df(1), du(1)
