name: Build dfc
on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
    - master
    - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
    steps:
    - uses: actions/checkout@v1
    - name: Create build directory
      run: test -d build || mkdir build
    - name: Run CMake
      run: cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_VERBOSE_MAKEFILE=YES -DNLS_ENABLED=false ..
    - name: Build
      run: make
